# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todo < Formula
  desc "A simple CLI tool to manage your todo list."
  homepage "https://github.com/AmanTahiliani/todo"
  version "0.3.3-alpha"
  license "MIT"

  on_macos do
    url "https://github.com/AmanTahiliani/todo/releases/download/v0.3.3-alpha/todo_Darwin_all.tar.gz"
    sha256 "d016e0e3f2c2ffeeb83117c60c3404466f626b8b6a40984c810c1d0aa4ec8c7b"

    def install
      bin.install "todo"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/AmanTahiliani/todo/releases/download/v0.3.3-alpha/todo_Linux_x86_64.tar.gz"
      sha256 "6ff26f5a3cc23ed76631adc4928503c63885d9655fee07d05e0c42dd68cd17a9"
      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/AmanTahiliani/todo/releases/download/v0.3.3-alpha/todo_Linux_arm64.tar.gz"
      sha256 "43ea5673764a41d2a6cf3bd537056d46fac3d3f8203d3cd46102e2347b78843b"
      def install
        bin.install "todo"
      end
    end
  end
end
